---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/aywsolution/public_html/oredis.aywsolution.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolution/oredis/
      - /bin/rsync -av ./ $DEPLOYPATH

