---
  deployment:
    tasks:
      #Para el dominio de aywsolution
      - export DEPLOYPATH=/home/aywsolution/public_html/oredis.aywsolution.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolution/oredis/
      - /bin/rsync -av ./ $DEPLOYPATH

      #Para el dominio de gorel
      # - export DEPLOYPATH=/home/gorel/public_html/oredis.regionloreto.gob.pe/
      # - /bin/rsync -av public/ $DEPLOYPATH
      # - export DEPLOYPATH=/home/gorel/oredis/
      # - /bin/rsync -av ./ $DEPLOYPATH
