version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oredis_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=gorel_oredis
      - DB_USERNAME=root
      - DB_PASSWORD=_35Tera41_/()
    networks:
      - oredis_laravel

  db:
    image: mysql:8.0
    container_name: oredis_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: _35Tera41_/()
      MYSQL_DATABASE: gorel_oredis
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - oredis_laravel

  nginx:
    image: nginx:latest
    container_name: oredis_nginx
    restart: unless-stopped
    ports:
      - "8180:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    networks:
      - oredis_laravel

networks:
  oredis_laravel:

volumes:
  dbdata:
